[[headers]]
  for = "/*"
  [headers.values]
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Embedder-Policy = "require-corp"

[[redirects]]
  from = "/share*ConwayGeomWasmWebMT.js"
  to = "/static/js/ConwayGeomWasmWebMT.js"
  status = 200
  force = true